name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
